openapi: 3.0.1
info:
  contact:
    email: apisupport@mastercard.com
    name: API Support
    url: https://developer.mastercard.com/support
  description: ATM Locations API
  title: ATM Locations API
  version: 2.0.0
servers:
- description: Production server
  url: https://api.mastercard.com/locations/atms
- description: Sandbox server
  url: https://sandbox.api.mastercard.com/locations/atms
tags:
- description: Retrieve a list of countries and country subdivisions
  name: Countries
- description: Retrieve ATM detail for a given geo location
  name: ATMs
paths:
  /countries:
    get:
      description: Returns a list of countries containing ATMs
      operationId: getCountries
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Countries'
          description: List of Countries
        "401":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-atms-api
                    ReasonCode: UNAUTHORIZED
                    Description: We couldn't recognize you
                    Recoverable: false
                    Details: Full authentication is required to access this resource
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication information was missing or invalid.
        "403":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-atms-api
                    ReasonCode: PERMISSION_DENIED
                    Description: You don't seem authorized to do that
                    Recoverable: false
                    Details: Reading ATM information requires readonly permissions
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Insufficient permissions for interacting with the resource.
      summary: Get a list of countries
      tags:
      - Countries
      x-accepts: application/json
  /country-subdivisions:
    get:
      description: Returns a list of country subdivisions for a given country
      operationId: getCountrySubdivisions
      parameters:
      - description: Country Code
        example: USA
        explode: true
        in: query
        name: country_code
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountrySubdivisions'
          description: List of Country Subdivisions
        "400":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: latitude
                    ReasonCode: INVALID_INPUT_VALUE
                    Description: Latitude is missing, invalid, or could not be determined
                      from address fields.
                    Recoverable: false
                    Details: null
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Something was wrong with the request.
        "401":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-atms-api
                    ReasonCode: UNAUTHORIZED
                    Description: We couldn't recognize you
                    Recoverable: false
                    Details: Full authentication is required to access this resource
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication information was missing or invalid.
        "403":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-atms-api
                    ReasonCode: PERMISSION_DENIED
                    Description: You don't seem authorized to do that
                    Recoverable: false
                    Details: Reading ATM information requires readonly permissions
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Insufficient permissions for interacting with the resource.
      summary: Get a list of country subdivisions
      tags:
      - Countries
      x-accepts: application/json
  /searches:
    post:
      description: Returns detailed information on ATMs based on the provided query
        parameters
      operationId: getAtms
      parameters:
      - description: The number of items to be retrieved
        example: 25
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: The page offset used for the query
        example: 1
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: Distance measurement for calculating the radius search. Optional
          The length of distance from the centroid point. Value string(<25). The default
          will be 5 units
        example: 5
        explode: true
        in: query
        name: distance
        required: false
        schema:
          type: integer
        style: form
      - description: Unit of measurement for calculating the radius search. Optional.
          Measurement of distance unit in miles or kilometers. Value string (MILE
          or KM)
        example: MILE
        explode: true
        in: query
        name: distance_unit
        required: false
        schema:
          enum:
          - MILE
          - KM
          type: string
        style: form
      requestBody:
        $ref: '#/components/requestBodies/AtmSearch'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Atms'
          description: List of ATM details
        "400":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: latitude
                    ReasonCode: INVALID_INPUT_VALUE
                    Description: Latitude is missing, invalid, or could not be determined
                      from address fields.
                    Recoverable: false
                    Details: null
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Something was wrong with the request.
        "401":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-atms-api
                    ReasonCode: UNAUTHORIZED
                    Description: We couldn't recognize you
                    Recoverable: false
                    Details: Full authentication is required to access this resource
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication information was missing or invalid.
        "403":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-atms-api
                    ReasonCode: PERMISSION_DENIED
                    Description: You don't seem authorized to do that
                    Recoverable: false
                    Details: Reading ATM information requires readonly permissions
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Insufficient permissions for interacting with the resource.
      summary: Get a list of ATM details
      tags:
      - ATMs
      x-contentType: application/json
      x-accepts: application/json
components:
  parameters:
    CountryParam:
      description: Country Code
      example: USA
      explode: true
      in: query
      name: country_code
      required: true
      schema:
        type: string
      style: form
    LimitParam:
      description: The number of items to be retrieved
      example: 25
      explode: true
      in: query
      name: limit
      required: false
      schema:
        type: integer
      style: form
    OffsetParam:
      description: The page offset used for the query
      example: 1
      explode: true
      in: query
      name: offset
      required: false
      schema:
        type: integer
      style: form
    DistanceParam:
      description: Distance measurement for calculating the radius search. Optional
        The length of distance from the centroid point. Value string(<25). The default
        will be 5 units
      example: 5
      explode: true
      in: query
      name: distance
      required: false
      schema:
        type: integer
      style: form
    DistanceUnitParam:
      description: Unit of measurement for calculating the radius search. Optional.
        Measurement of distance unit in miles or kilometers. Value string (MILE or
        KM)
      example: MILE
      explode: true
      in: query
      name: distance_unit
      required: false
      schema:
        enum:
        - MILE
        - KM
        type: string
      style: form
  requestBodies:
    AtmSearch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AtmSearch'
      description: A JSON object containing item data
      required: true
  responses:
    Countries:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Countries'
      description: List of Countries
    CountrySubdivisions:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CountrySubdivisions'
      description: List of Country Subdivisions
    Atms:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Atms'
      description: List of ATM details
    BadRequestError:
      content:
        application/json:
          example:
            Errors:
            - Error:
                Source: latitude
                ReasonCode: INVALID_INPUT_VALUE
                Description: Latitude is missing, invalid, or could not be determined
                  from address fields.
                Recoverable: false
                Details: null
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Something was wrong with the request.
    UnauthorizedError:
      content:
        application/json:
          example:
            Errors:
            - Error:
                Source: locations-atms-api
                ReasonCode: UNAUTHORIZED
                Description: We couldn't recognize you
                Recoverable: false
                Details: Full authentication is required to access this resource
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Authentication information was missing or invalid.
    ForbiddenError:
      content:
        application/json:
          example:
            Errors:
            - Error:
                Source: locations-atms-api
                ReasonCode: PERMISSION_DENIED
                Description: You don't seem authorized to do that
                Recoverable: false
                Details: Reading ATM information requires readonly permissions
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Insufficient permissions for interacting with the resource.
  schemas:
    Country:
      description: Available information for the Country such as the name and code
      example:
        Country:
          countryCode: AUS
          countryName: Australia
      properties:
        countryCode:
          description: Three digit alpha country code as defined in ISO 3166-1
          example: AUS
          maxLength: 3
          minLength: 3
          type: string
        countryName:
          description: Name of the country
          example: Australia
          type: string
      type: object
    CountrySubdivision:
      description: Available information the Country Subdivision such as the name
        and code
      example:
        CountrySubdivision:
          countrySubdivisionCode: AL
          countrySubdivisionName: Alabama
      properties:
        countrySubdivisionCode:
          description: Abbreviated code for the state or province
          example: AL
          maxLength: 2
          minLength: 2
          type: string
        countrySubdivisionName:
          description: Name of the country subdivision
          example: Alabama
          type: string
      type: object
    AtmSearch:
      description: Atm Search Request Info
      example:
        city: SAINT PETERS
        countryCode: USA
        latitude: "38.794676"
        postalCode: "63376"
        countrySubdivisionCode: MO
        addressLine1: 4033 Veterans Memorial Pkwy
        addressLine2: ""
        longitude: -90.5689
      properties:
        addressLine1:
          description: Line 1 of the street address for the ATM location. Usually
            includes the street number and name. This parameter is ignored if latitude
            and longitude are provided. If you provide this parameter you must also
            provide the Country parameter and either City parameter or PostalCode
            parameter.
          example: 4033 Veterans Memorial Pkwy
          type: string
        addressLine2:
          description: Line 2 of the street address usually an apartment number or
            suite number. This parameter is used rarely and is ignored if latitude
            and longitude are provided. If you provide this parameter you must also
            provide the Country parameter and either City parameter or PostalCode
            parameter.
          example: ""
          type: string
        city:
          description: The name of the city for a ATM location. This parameter is
            ignored if latitude and longitude are provided. If you provide this parameter
            you must also provide the Country parameter.
          example: SAINT PETERS
          type: string
        countryCode:
          description: Any three character country code for an ATM location. Valid
            values are three digit alpha country codes. This parameter is ignored
            if latitude and longitude are provided. This parameter is required if
            any other address information is provided including AddressLine1 AddressLine2
            City PostalCode or CountrySubdivision.
          example: USA
          type: string
        countrySubdivisionCode:
          description: The state or province for an ATM location (only supported for
            US and Canada locations). This parameter is ignored if latitude and longitude
            are provided. If you provide this parameter you must also provide the
            Country parameter.
          example: MO
          type: string
        latitude:
          description: The latitude of a ATM location. If latitude is provided longitude
            must also be provided.
          example: "38.794676"
          type: string
        longitude:
          description: The longitude of a ATM location. If longitude is provided latitude
            must also be provided.
          example: -90.5689
          type: string
        postalCode:
          description: The zip code or postal code for an ATM location. This parameter
            is ignored if latitude and longitude are provided. If you provide this
            parameter you must also provide the Country parameter.
          example: "63376"
          type: string
      title: AtmSearch
      type: object
    Atm:
      description: ATM detail information
      example:
        handicapAccessible: IS_HANDICAP_ACCESSIBLE
        distanceUnit: MILE
        sponsor: That Bank LLC
        sponsorICA: "9386"
        countrySubdivisionName: Missouri
        isSurchargeFreeAlliance: "YES"
        routeTransactionNumber: "840180546"
        distance: 1.75723000000001
        city: OFallon
        latitude: "38.670337"
        postalCode: "63366"
        locationType: FINANCIAL_INSTITUTION
        availability: BUSINESS_HOURS
        accessFees: DOMESTIC
        countryCode: USA
        countrySubdivisionCode: MO
        addressLine1: 1 Oak Street
        addressLine2: Apt 1
        camera: "NO"
        longitude: -90.443727
        supportsEmv: SUPPORTS_EMV
        owner: That Bank LLC
        hasSharedDeposit: "YES"
        atmTerminalId: NH044143
        locationName: That Bank
        surchargeFreeAllianceNetwork: DOES_NOT_PARTICIPATE_IN_SFA
        geocodingResult: G3
        ownerICA: "9386"
        airportCode: STL
        countryName: United States
      properties:
        accessFees:
          description: This value indicates under what conditions access fees are
            charged. Options are UNKNOWN, DOMESTIC, INTERNATIONAL, DOMESTIC_AND_INTERNATIONAL,
            NO_FEE.
          example: DOMESTIC
          type: string
        addressLine1:
          description: Line 1 of the street address for the ATM location. Usually
            includes the street number and name.
          example: 1 Oak Street
          type: string
        addressLine2:
          description: Line 2 of the street address usually an apartment number or
            suite number.
          example: Apt 1
          type: string
        airportCode:
          description: The Airport Code
          example: STL
          type: string
        atmTerminalId:
          description: The ATM Terminal Id
          example: NH044143
          type: string
        availability:
          description: This value indicates the availability hours of the ATM. Options
            are UNKNOWN, ALWAYS_AVAILABLE, BUSINESS_HOURS, IRREGULAR_HOURS.
          example: BUSINESS_HOURS
          type: string
        camera:
          description: This value indicates whether or not a security camera is present
            or near ATM
          example: "NO"
          type: string
        countryCode:
          description: Three digit alpha country code as defined in ISO
          example: USA
          type: string
        countryName:
          description: Name of the country.
          example: United States
          type: string
        countrySubdivisionCode:
          description: Code of the state or province for an ATM location.
          example: MO
          type: string
        countrySubdivisionName:
          description: Name of the state or province for an ATM location.
          example: Missouri
          type: string
        city:
          description: The name of the city for an ATM location.
          example: OFallon
          type: string
        distance:
          description: This is the numerical value for the distance from the provided
            location to the selected ATM.
          example: 1.75723000000001
          format: double
          type: number
        distanceUnit:
          description: This is the unit of measure value for the distance from the
            provided location to the selected ATM. Options are KM and MILE.
          example: MILE
          type: string
        geocodingResult:
          description: GeocodingResult for the ATM
          example: G3
          type: string
        handicapAccessible:
          description: This indicates whether the ATM has the ability to read chip
            cards or not. Options are UNKNOWN, IS_HANDICAP_ACCESSIBLE, NOT_HANDICAP_ACCESSIBLE.
          example: IS_HANDICAP_ACCESSIBLE
          type: string
        hasSharedDeposit:
          description: This value indicates whether or not the ATM participates in
            the MasterCard Shared Deposit network. Options are YES or NO.
          example: "YES"
          type: string
        isSurchargeFreeAlliance:
          description: This value indicates whether or not the ATM participates in
            the MasterCard Shared (only) Surcharge Free Alliance network. Options
            are YES or NO.
          example: "YES"
          type: string
        latitude:
          description: The latitude of the ATM
          example: "38.670337"
          type: string
        locationName:
          description: The name of the ATM location
          example: That Bank
          type: string
        locationType:
          description: Type of location for the ATM. Options are OTHER, AIRPORT, HOSPITAL,
            FINANCIAL_INSTITUTION.
          example: FINANCIAL_INSTITUTION
          type: string
        longitude:
          description: The longitude of the ATM.
          example: -90.443727
          type: string
        owner:
          description: This is the DBA name of the financial institution affiliate
            or independent service organization.
          example: That Bank LLC
          type: string
        ownerICA:
          description: This is the ICA of the entity that owns the ATM
          example: "9386"
          type: string
        postalCode:
          description: The postal code of the ATM location.
          example: "63366"
          type: string
        routeTransactionNumber:
          description: The routing transaction number
          example: "840180546"
          type: string
        sponsor:
          description: This is the legal or business name of the entity that sponsors
            the owner of the ATM into the MasterCard network.
          example: That Bank LLC
          type: string
        sponsorICA:
          description: This is the ICA of entity that sponsors the owner of the ATM
          example: "9386"
          type: string
        supportsEmv:
          description: This indicates whether the ATM has the ability to read chip
            cards or not. Options are UNKNOWN, SUPPORTS_EMV, DOES_NOT_SUPPORT_EMV.
          example: SUPPORTS_EMV
          type: string
        surchargeFreeAllianceNetwork:
          description: This value indicates whether or not the ATM participates in
            the MasterCard Shared (only) Surcharge Free Alliance network. Options
            are DOES_NOT_PARTICIPATE_IN_SFA, ALLPOINT_PREPAID, MONEYPASS_DEBIT, and
            ALL_SURCHARGE_FREE.
          example: DOES_NOT_PARTICIPATE_IN_SFA
          type: string
      title: ATM
      type: object
    Atms:
      example:
        total: 210
        offset: 1
        atms:
        - handicapAccessible: IS_HANDICAP_ACCESSIBLE
          distanceUnit: MILE
          sponsor: That Bank LLC
          sponsorICA: "9386"
          countrySubdivisionName: Missouri
          isSurchargeFreeAlliance: "YES"
          routeTransactionNumber: "840180546"
          distance: 1.75723000000001
          city: OFallon
          latitude: "38.670337"
          postalCode: "63366"
          locationType: FINANCIAL_INSTITUTION
          availability: BUSINESS_HOURS
          accessFees: DOMESTIC
          countryCode: USA
          countrySubdivisionCode: MO
          addressLine1: 1 Oak Street
          addressLine2: Apt 1
          camera: "NO"
          longitude: -90.443727
          supportsEmv: SUPPORTS_EMV
          owner: That Bank LLC
          hasSharedDeposit: "YES"
          atmTerminalId: NH044143
          locationName: That Bank
          surchargeFreeAllianceNetwork: DOES_NOT_PARTICIPATE_IN_SFA
          geocodingResult: G3
          ownerICA: "9386"
          airportCode: STL
          countryName: United States
        - handicapAccessible: IS_HANDICAP_ACCESSIBLE
          distanceUnit: MILE
          sponsor: That Bank LLC
          sponsorICA: "9386"
          countrySubdivisionName: Missouri
          isSurchargeFreeAlliance: "YES"
          routeTransactionNumber: "840180546"
          distance: 1.75723000000001
          city: OFallon
          latitude: "38.670337"
          postalCode: "63366"
          locationType: FINANCIAL_INSTITUTION
          availability: BUSINESS_HOURS
          accessFees: DOMESTIC
          countryCode: USA
          countrySubdivisionCode: MO
          addressLine1: 1 Oak Street
          addressLine2: Apt 1
          camera: "NO"
          longitude: -90.443727
          supportsEmv: SUPPORTS_EMV
          owner: That Bank LLC
          hasSharedDeposit: "YES"
          atmTerminalId: NH044143
          locationName: That Bank
          surchargeFreeAllianceNetwork: DOES_NOT_PARTICIPATE_IN_SFA
          geocodingResult: G3
          ownerICA: "9386"
          airportCode: STL
          countryName: United States
        count: 10
        limit: 10
      properties:
        count:
          description: The number of items in the retrieved data set
          example: 10
          format: int32
          type: integer
        limit:
          description: The number of items requested to be retrieved
          example: 10
          format: int32
          type: integer
        offset:
          description: The page offset used for the query
          example: 1
          format: int32
          type: integer
        total:
          description: The total number of ATMs available to be retrieved
          example: 210
          format: int32
          type: integer
        atms:
          description: The list of ATMs retrieved
          items:
            $ref: '#/components/schemas/Atm'
          type: array
      title: Atms
      type: object
    Error:
      description: Details of the error condition such as the source of the error,
        reason code for the error, if the error is recoverable, and details about
        the error
      properties:
        Source:
          description: The application that generated this error
          example: latitude
          maxLength: 150
          minLength: 0
          type: string
        ReasonCode:
          description: A unique constant identifying the error case encountered during
            transaction processing
          example: INVALID_INPUT_VALUE
          maxLength: 150
          minLength: 0
          type: string
        Description:
          description: Short description of the ReasonCode field
          example: Latitude is missing, invalid, or could not be determined from address
            fields.
          maxLength: 150
          minLength: 0
          type: string
        Recoverable:
          description: Indicates whether this error will always be returned for this
            request, or retrying could change the outcome
          example: false
          type: boolean
        Details:
          description: Description of the issue
          example: Latitude is missing, invalid, or could not be determined from address
            fields.
          maxLength: 150
          minLength: 0
          nullable: true
          type: string
      required:
      - Description
      - ReasonCode
      - Recoverable
      - Source
      type: object
    ErrorResponse:
      description: Only returned in the event of an error condition
      properties:
        Errors:
          $ref: '#/components/schemas/Errors'
      required:
      - Errors
      type: object
    Errors:
      description: Only returned in the event of an error condition
      example:
        Errors:
        - Error:
            Source: latitude
            ReasonCode: INVALID_INPUT_VALUE
            Description: Latitude is missing, invalid, or could not be determined
              from address fields.
            Recoverable: false
            Details: null
      properties:
        Error:
          description: An error object
          example:
          - Error:
              Source: latitude
              ReasonCode: INVALID_INPUT_VALUE
              Description: Latitude is missing, invalid, or could not be determined
                from address fields.
              Recoverable: false
              Details: null
          items:
            $ref: '#/components/schemas/Error'
          type: array
      required:
      - Error
      type: object
    Countries:
      description: List of countries
      example:
        countries:
        - countryName: United States
          countryCode: USA
      properties:
        countries:
          description: countries
          example:
          - countryName: United States
            countryCode: USA
          items:
            $ref: '#/components/schemas/Country'
          type: array
      type: object
    CountrySubdivisions:
      description: List of country subdivisions
      example:
        countrySubdivisions:
        - countrySubdivisionName: Alabama
          countrySubdivisionCode: AL
      properties:
        countrySubdivisions:
          description: countrySubdivisions
          example:
          - countrySubdivisionName: Alabama
            countrySubdivisionCode: AL
          items:
            $ref: '#/components/schemas/CountrySubdivision'
          type: array
      type: object

